// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtI_l5tnl0WKDipNNqYi_9eebARAOTWOE',
    appId: '1:368537736108:web:72d9f21a53f6e8236d2009',
    messagingSenderId: '368537736108',
    projectId: 'ccs-sep',
    authDomain: 'ccs-sep.firebaseapp.com',
    storageBucket: 'ccs-sep.firebasestorage.app',
    measurementId: 'G-8YBHZHVHHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGxqoPnqGAA8w2Dw-wnPscVffjNMpg5uE',
    appId: '1:368537736108:android:125c7100790db87e6d2009',
    messagingSenderId: '368537736108',
    projectId: 'ccs-sep',
    storageBucket: 'ccs-sep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI4WY8uLuCY3PCt3_ALJFKmbJIos8mX_w',
    appId: '1:368537736108:ios:051aeecba6bff4b66d2009',
    messagingSenderId: '368537736108',
    projectId: 'ccs-sep',
    storageBucket: 'ccs-sep.firebasestorage.app',
    iosBundleId: 'com.example.sepModuleRazzaq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI4WY8uLuCY3PCt3_ALJFKmbJIos8mX_w',
    appId: '1:368537736108:ios:051aeecba6bff4b66d2009',
    messagingSenderId: '368537736108',
    projectId: 'ccs-sep',
    storageBucket: 'ccs-sep.firebasestorage.app',
    iosBundleId: 'com.example.sepModuleRazzaq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtI_l5tnl0WKDipNNqYi_9eebARAOTWOE',
    appId: '1:368537736108:web:7857254e4cf72e996d2009',
    messagingSenderId: '368537736108',
    projectId: 'ccs-sep',
    authDomain: 'ccs-sep.firebaseapp.com',
    storageBucket: 'ccs-sep.firebasestorage.app',
    measurementId: 'G-DP8SWP0JSF',
  );
}
